# --- !Ups

CREATE TABLE TEAM (
  ID       INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY   (ID),
  NAME          VARCHAR(50)
);

CREATE TABLE PLAYER (
  ID    INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID),
  NAME         VARCHAR(50)
);

CREATE TABLE TEAM_PLAYER (
  TEAM_ID        INT UNSIGNED NOT NULL,
  PLAYER_ID         INT UNSIGNED NOT NULL,
  CREATION_DATE   DATE,
  PRIMARY KEY (TEAM_ID, PLAYER_ID),
  CONSTRAINT team_player_fk1 FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID),
  CONSTRAINT team_player_fk2 FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID)
);

CREATE TABLE MATCH (
  ID    INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID),
  START_DATE  DATETIME,
  END_DATE    DATETIME
);

CREATE TABLE MATCH_TEAM (
  MATCH_ID        INT UNSIGNED NOT NULL,
  TEAM_ID         INT UNSIGNED NOT NULL,
  CREATION_DATE   DATE,
  PRIMARY KEY (TEAM_ID, MATCH_ID),
--  KEY MATCH_ID (MATCH_ID),
--  KEY TEAM_ID (TEAM_ID),
  CONSTRAINT match_team_fk1 FOREIGN KEY (MATCH_ID) REFERENCES MATCH (ID),
  CONSTRAINT match_team_fk2 FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID)
  );


# --- !Downs

SET REFERENTIAL_INTEGRITY FALSE;

drop table if exists PLAYER;
drop table if exists TEAM;
drop table if exists TEAM_PLAYER;
drop table if exists MATCH;
drop table if exists MATCH_TEAM;

SET REFERENTIAL_INTEGRITY TRUE;
