# --- !Ups

CREATE TABLE PLAYER (
  PLAYER_ID    INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (PLAYER_ID),
  NAME         VARCHAR(50),
);

# --- !Downs

SET REFERENTIAL_INTEGRITY FALSE;

drop table if exists PLAYER;

SET REFERENTIAL_INTEGRITY TRUE;
